trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true
  - task: AzureStaticWebApp@0
    inputs:
      app_location: 'Client'
      api_location: 'Api'
      output_location: 'wwwroot'
      azure_static_web_apps_api_token: $(deployToken)